// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from layer_gps.djinni

#pragma once

#include <utility>

struct GpsCourseInfo final {
    float angle;
    float scaling;

    GpsCourseInfo(float angle_,
                  float scaling_)
    : angle(std::move(angle_))
    , scaling(std::move(scaling_))
    {}
};
