// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from layer_gps.djinni

#pragma once

#include "Coord.h"

enum class GpsMode;

class GpsLayerCallbackInterface {
public:
    virtual ~GpsLayerCallbackInterface() = default;

    virtual void modeDidChange(GpsMode mode) = 0;

    virtual void onPointClick(const ::Coord & coordinate) = 0;
};
