// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from layer_gps.djinni

#pragma once

#include "Color.h"
#include "TextureHolderInterface.h"
#include <memory>

class GpsLayerCallbackInterface {
public:
    virtual ~GpsLayerCallbackInterface() {}

    virtual std::shared_ptr<::TextureHolderInterface> pointImage() = 0;

    virtual std::shared_ptr<::TextureHolderInterface> headingImage() = 0;

    virtual ::Color accuracyColor() = 0;
};
