// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from layer_gps.djinni

#include "NativeGpsLayerCallbackInterface.h"  // my header
#include "NativeColor.h"
#include "NativeTextureHolderInterface.h"

namespace djinni_generated {

NativeGpsLayerCallbackInterface::NativeGpsLayerCallbackInterface() : ::djinni::JniInterface<::GpsLayerCallbackInterface, NativeGpsLayerCallbackInterface>("io/openmobilemaps/mapscore/shared/gps/GpsLayerCallbackInterface$CppProxy") {}

NativeGpsLayerCallbackInterface::~NativeGpsLayerCallbackInterface() = default;

NativeGpsLayerCallbackInterface::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeGpsLayerCallbackInterface::JavaProxy::~JavaProxy() = default;

std::shared_ptr<::TextureHolderInterface> NativeGpsLayerCallbackInterface::JavaProxy::pointImage() {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeGpsLayerCallbackInterface>::get();
    auto jret = jniEnv->CallObjectMethod(Handle::get().get(), data.method_pointImage);
    ::djinni::jniExceptionCheck(jniEnv);
    return ::djinni_generated::NativeTextureHolderInterface::toCpp(jniEnv, jret);
}
std::shared_ptr<::TextureHolderInterface> NativeGpsLayerCallbackInterface::JavaProxy::headingImage() {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeGpsLayerCallbackInterface>::get();
    auto jret = jniEnv->CallObjectMethod(Handle::get().get(), data.method_headingImage);
    ::djinni::jniExceptionCheck(jniEnv);
    return ::djinni_generated::NativeTextureHolderInterface::toCpp(jniEnv, jret);
}
::Color NativeGpsLayerCallbackInterface::JavaProxy::accuracyColor() {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeGpsLayerCallbackInterface>::get();
    auto jret = jniEnv->CallObjectMethod(Handle::get().get(), data.method_accuracyColor);
    ::djinni::jniExceptionCheck(jniEnv);
    return ::djinni_generated::NativeColor::toCpp(jniEnv, jret);
}

CJNIEXPORT void JNICALL Java_io_openmobilemaps_mapscore_shared_gps_GpsLayerCallbackInterface_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::GpsLayerCallbackInterface>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT ::djinni_generated::NativeTextureHolderInterface::JniType JNICALL Java_io_openmobilemaps_mapscore_shared_gps_GpsLayerCallbackInterface_00024CppProxy_native_1pointImage(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::GpsLayerCallbackInterface>(nativeRef);
        auto r = ref->pointImage();
        return ::djinni::release(::djinni_generated::NativeTextureHolderInterface::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT ::djinni_generated::NativeTextureHolderInterface::JniType JNICALL Java_io_openmobilemaps_mapscore_shared_gps_GpsLayerCallbackInterface_00024CppProxy_native_1headingImage(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::GpsLayerCallbackInterface>(nativeRef);
        auto r = ref->headingImage();
        return ::djinni::release(::djinni_generated::NativeTextureHolderInterface::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT ::djinni_generated::NativeColor::JniType JNICALL Java_io_openmobilemaps_mapscore_shared_gps_GpsLayerCallbackInterface_00024CppProxy_native_1accuracyColor(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::GpsLayerCallbackInterface>(nativeRef);
        auto r = ref->accuracyColor();
        return ::djinni::release(::djinni_generated::NativeColor::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace djinni_generated
