// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from layer_gps.djinni

#include "NativeGpsCourseInfo.h"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeGpsCourseInfo::NativeGpsCourseInfo() = default;

NativeGpsCourseInfo::~NativeGpsCourseInfo() = default;

auto NativeGpsCourseInfo::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeGpsCourseInfo>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::F32::fromCpp(jniEnv, c.angle)),
                                                           ::djinni::get(::djinni::F32::fromCpp(jniEnv, c.scaling)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeGpsCourseInfo::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 3);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeGpsCourseInfo>::get();
    return {::djinni::F32::toCpp(jniEnv, jniEnv->GetFloatField(j, data.field_angle)),
            ::djinni::F32::toCpp(jniEnv, jniEnv->GetFloatField(j, data.field_scaling))};
}

} // namespace djinni_generated
