// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from layer_gps.djinni

#pragma once

#include "GpsLayerCallbackInterface.h"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeGpsLayerCallbackInterface final : ::djinni::JniInterface<::GpsLayerCallbackInterface, NativeGpsLayerCallbackInterface> {
public:
    using CppType = std::shared_ptr<::GpsLayerCallbackInterface>;
    using CppOptType = std::shared_ptr<::GpsLayerCallbackInterface>;
    using JniType = jobject;

    using Boxed = NativeGpsLayerCallbackInterface;

    ~NativeGpsLayerCallbackInterface();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeGpsLayerCallbackInterface>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeGpsLayerCallbackInterface>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeGpsLayerCallbackInterface();
    friend ::djinni::JniClass<NativeGpsLayerCallbackInterface>;
    friend ::djinni::JniInterface<::GpsLayerCallbackInterface, NativeGpsLayerCallbackInterface>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::GpsLayerCallbackInterface
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        std::shared_ptr<::TextureHolderInterface> pointImage() override;
        std::shared_ptr<::TextureHolderInterface> headingImage() override;
        ::Color accuracyColor() override;

    private:
        friend ::djinni::JniInterface<::GpsLayerCallbackInterface, ::djinni_generated::NativeGpsLayerCallbackInterface>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("io/openmobilemaps/mapscore/shared/gps/GpsLayerCallbackInterface") };
    const jmethodID method_pointImage { ::djinni::jniGetMethodID(clazz.get(), "pointImage", "()Lio/openmobilemaps/mapscore/shared/graphics/objects/TextureHolderInterface;") };
    const jmethodID method_headingImage { ::djinni::jniGetMethodID(clazz.get(), "headingImage", "()Lio/openmobilemaps/mapscore/shared/graphics/objects/TextureHolderInterface;") };
    const jmethodID method_accuracyColor { ::djinni::jniGetMethodID(clazz.get(), "accuracyColor", "()Lio/openmobilemaps/mapscore/shared/graphics/common/Color;") };
};

}  // namespace djinni_generated
