// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from layer_gps.djinni

package io.openmobilemaps.gps.shared.gps

data class GpsCourseInfo(
    var angle: Float,
    var scaling: Float,
)