// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from layer_gps.djinni

package io.openmobilemaps.gps.shared.gps

import com.snapchat.djinni.NativeObjectManager
import java.util.concurrent.atomic.AtomicBoolean

abstract class GpsLayerCallbackInterface {

    abstract fun modeDidChange(mode: GpsMode)

    abstract fun onPointClick(coordinate: io.openmobilemaps.mapscore.shared.map.coordinates.Coord)

    private class CppProxy : GpsLayerCallbackInterface {
        private val nativeRef: Long
        private val destroyed: AtomicBoolean = AtomicBoolean(false)

        private constructor(nativeRef: Long) {
            if (nativeRef == 0L) error("nativeRef is zero")
            this.nativeRef = nativeRef
            NativeObjectManager.register(this, nativeRef)
        }

        external fun nativeDestroy(nativeRef: Long)

        override fun modeDidChange(mode: GpsMode) {
            assert(!this.destroyed.get()) { error("trying to use a destroyed object") }
            native_modeDidChange(this.nativeRef, mode)
        }
        private external fun native_modeDidChange(_nativeRef: Long, mode: GpsMode)

        override fun onPointClick(coordinate: io.openmobilemaps.mapscore.shared.map.coordinates.Coord) {
            assert(!this.destroyed.get()) { error("trying to use a destroyed object") }
            native_onPointClick(this.nativeRef, coordinate)
        }
        private external fun native_onPointClick(_nativeRef: Long, coordinate: io.openmobilemaps.mapscore.shared.map.coordinates.Coord)
    }
}
