// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from layer_gps.djinni

#import "MCGpsMode.h"
#import <Foundation/Foundation.h>


@protocol MCGpsLayerCallbackInterface

- (void)modeDidChange:(MCGpsMode)mode;

@end
