// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from layer_gps.djinni

#import "MCColor.h"
#import "MCTextureHolderInterface.h"
#import <Foundation/Foundation.h>


@protocol MCGpsLayerCallbackInterface

- (nullable id<MCTextureHolderInterface>)pointImage;

- (nullable id<MCTextureHolderInterface>)headingImage;

- (nonnull MCColor *)accuracyColor;

@end
