// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from layer_gps.djinni

#import "MCCoord.h"
#import "MCGpsMode.h"
#import "MCGpsStyleInfo.h"
#import "MCLayerInterface.h"
#import <Foundation/Foundation.h>
@class MCGpsLayerInterface;


@interface MCGpsLayerInterface : NSObject

+ (nullable MCGpsLayerInterface *)create:(nonnull MCGpsStyleInfo *)styleInfo;

- (void)setMode:(MCGpsMode)mode;

- (MCGpsMode)getMode;

- (void)updatePosition:(nonnull MCCoord *)position
   horizontalAccuracyM:(double)horizontalAccuracyM;

- (void)updateHeading:(float)angleHeading;

- (nullable id<MCLayerInterface>)asLayerInterface;

@end
