// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from layer_gps.djinni

#import "MCGpsStyleInfo+Private.h"
#import "DJIMarshal+Private.h"
#import "MCColor+Private.h"
#import "MCTextureHolderInterface+Private.h"
#include <cassert>

namespace djinni_generated {

auto GpsStyleInfo::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::Optional<std::optional, ::djinni_generated::TextureHolderInterface>::toCpp(obj.pointTexture),
            ::djinni::Optional<std::optional, ::djinni_generated::TextureHolderInterface>::toCpp(obj.headingTexture),
            ::djinni::Optional<std::optional, ::djinni_generated::TextureHolderInterface>::toCpp(obj.courseTexture),
            ::djinni_generated::Color::toCpp(obj.accuracyColor)};
}

auto GpsStyleInfo::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[MCGpsStyleInfo alloc] initWithPointTexture:(::djinni::Optional<std::optional, ::djinni_generated::TextureHolderInterface>::fromCpp(cpp.pointTexture))
                                         headingTexture:(::djinni::Optional<std::optional, ::djinni_generated::TextureHolderInterface>::fromCpp(cpp.headingTexture))
                                          courseTexture:(::djinni::Optional<std::optional, ::djinni_generated::TextureHolderInterface>::fromCpp(cpp.courseTexture))
                                          accuracyColor:(::djinni_generated::Color::fromCpp(cpp.accuracyColor))];
}

} // namespace djinni_generated
