// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from layer_gps.djinni

#import "MCGpsCourseInfo.h"


@implementation MCGpsCourseInfo

- (nonnull instancetype)initWithAngle:(float)angle
                              scaling:(float)scaling
{
    if (self = [super init]) {
        _angle = angle;
        _scaling = scaling;
    }
    return self;
}

+ (nonnull instancetype)gpsCourseInfoWithAngle:(float)angle
                                       scaling:(float)scaling
{
    return [[self alloc] initWithAngle:angle
                               scaling:scaling];
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p angle:%@ scaling:%@>", self.class, (void *)self, @(self.angle), @(self.scaling)];
}

#endif
@end
