// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from layer_gps.djinni

#import "MCGpsStyleInfo.h"


@implementation MCGpsStyleInfo

- (nonnull instancetype)initWithPointTexture:(nullable id<MCTextureHolderInterface>)pointTexture
                              headingTexture:(nullable id<MCTextureHolderInterface>)headingTexture
                               accuracyColor:(nonnull MCColor *)accuracyColor
{
    if (self = [super init]) {
        _pointTexture = pointTexture;
        _headingTexture = headingTexture;
        _accuracyColor = accuracyColor;
    }
    return self;
}

+ (nonnull instancetype)gpsStyleInfoWithPointTexture:(nullable id<MCTextureHolderInterface>)pointTexture
                                      headingTexture:(nullable id<MCTextureHolderInterface>)headingTexture
                                       accuracyColor:(nonnull MCColor *)accuracyColor
{
    return [[self alloc] initWithPointTexture:pointTexture
                               headingTexture:headingTexture
                                accuracyColor:accuracyColor];
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p pointTexture:%@ headingTexture:%@ accuracyColor:%@>", self.class, (void *)self, self.pointTexture, self.headingTexture, self.accuracyColor];
}

#endif
@end
