// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from layer_gps.djinni
#ifdef __cplusplus
#ifndef __OBJC__

#include "GpsMode.h"
#import "DJIMarshal+Private.h"

#endif
#endif
