// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from layer_gps.djinni

#import "MCColor.h"
#import "MCTextureHolderInterface.h"
#import "MCVec2D.h"
#import <Foundation/Foundation.h>

@interface MCGpsStyleInfo : NSObject
- (nonnull instancetype)initWithPointTexture:(nullable id<MCTextureHolderInterface>)pointTexture
                                 pointSizePx:(nonnull MCVec2D *)pointSizePx
                              headingTexture:(nullable id<MCTextureHolderInterface>)headingTexture
                               headingSizePx:(nonnull MCVec2D *)headingSizePx
                               accuracyColor:(nonnull MCColor *)accuracyColor;
+ (nonnull instancetype)gpsStyleInfoWithPointTexture:(nullable id<MCTextureHolderInterface>)pointTexture
                                         pointSizePx:(nonnull MCVec2D *)pointSizePx
                                      headingTexture:(nullable id<MCTextureHolderInterface>)headingTexture
                                       headingSizePx:(nonnull MCVec2D *)headingSizePx
                                       accuracyColor:(nonnull MCColor *)accuracyColor;

@property (nonatomic, readonly, nullable) id<MCTextureHolderInterface> pointTexture;

@property (nonatomic, readonly, nonnull) MCVec2D * pointSizePx;

@property (nonatomic, readonly, nullable) id<MCTextureHolderInterface> headingTexture;

@property (nonatomic, readonly, nonnull) MCVec2D * headingSizePx;

@property (nonatomic, readonly, nonnull) MCColor * accuracyColor;

@end
