// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from layer_gps.djinni

#import "MCGpsLayerCallbackInterface+Private.h"
#import "MCGpsLayerCallbackInterface.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIObjcWrapperCache+Private.h"
#import "MCColor+Private.h"
#import "MCTextureHolderInterface+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface MCGpsLayerCallbackInterfaceCppProxy : NSObject<MCGpsLayerCallbackInterface>

- (id)initWithCpp:(const std::shared_ptr<::GpsLayerCallbackInterface>&)cppRef;

@end

@implementation MCGpsLayerCallbackInterfaceCppProxy {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::GpsLayerCallbackInterface>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::GpsLayerCallbackInterface>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (nullable id<MCTextureHolderInterface>)pointImage {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->pointImage();
        return ::djinni_generated::TextureHolderInterface::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nullable id<MCTextureHolderInterface>)headingImage {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->headingImage();
        return ::djinni_generated::TextureHolderInterface::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull MCColor *)accuracyColor {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->accuracyColor();
        return ::djinni_generated::Color::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

class GpsLayerCallbackInterface::ObjcProxy final
: public ::GpsLayerCallbackInterface
, private ::djinni::ObjcProxyBase<ObjcType>
{
    friend class ::djinni_generated::GpsLayerCallbackInterface;
public:
    using ObjcProxyBase::ObjcProxyBase;
    std::shared_ptr<::TextureHolderInterface> pointImage() override
    {
        @autoreleasepool {
            auto objcpp_result_ = [djinni_private_get_proxied_objc_object() pointImage];
            return ::djinni_generated::TextureHolderInterface::toCpp(objcpp_result_);
        }
    }
    std::shared_ptr<::TextureHolderInterface> headingImage() override
    {
        @autoreleasepool {
            auto objcpp_result_ = [djinni_private_get_proxied_objc_object() headingImage];
            return ::djinni_generated::TextureHolderInterface::toCpp(objcpp_result_);
        }
    }
    ::Color accuracyColor() override
    {
        @autoreleasepool {
            auto objcpp_result_ = [djinni_private_get_proxied_objc_object() accuracyColor];
            return ::djinni_generated::Color::toCpp(objcpp_result_);
        }
    }
};

}  // namespace djinni_generated

namespace djinni_generated {

auto GpsLayerCallbackInterface::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    if ([(id)objc isKindOfClass:[MCGpsLayerCallbackInterfaceCppProxy class]]) {
        return ((MCGpsLayerCallbackInterfaceCppProxy*)objc)->_cppRefHandle.get();
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto GpsLayerCallbackInterface::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    if (auto cppPtr = dynamic_cast<ObjcProxy*>(cpp.get())) {
        return cppPtr->djinni_private_get_proxied_objc_object();
    }
    return ::djinni::get_cpp_proxy<MCGpsLayerCallbackInterfaceCppProxy>(cpp);
}

}  // namespace djinni_generated

@end
