// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from layer_gps.djinni

#import "MCColor.h"
#import "MCTextureHolderInterface.h"
#import <Foundation/Foundation.h>

@interface MCGpsStyleInfo : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithPointTexture:(nullable id<MCTextureHolderInterface>)pointTexture
                              headingTexture:(nullable id<MCTextureHolderInterface>)headingTexture
                               accuracyColor:(nonnull MCColor *)accuracyColor NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)gpsStyleInfoWithPointTexture:(nullable id<MCTextureHolderInterface>)pointTexture
                                      headingTexture:(nullable id<MCTextureHolderInterface>)headingTexture
                                       accuracyColor:(nonnull MCColor *)accuracyColor;

@property (nonatomic, readonly, nullable) id<MCTextureHolderInterface> pointTexture;

@property (nonatomic, readonly, nullable) id<MCTextureHolderInterface> headingTexture;

@property (nonatomic, readonly, nonnull) MCColor * accuracyColor;

@end
