// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from layer_gps.djinni

#import "MCGpsStyleInfo+Private.h"
#import "DJIMarshal+Private.h"
#import "MCColor+Private.h"
#import "MCTextureHolderInterface+Private.h"
#import "MCVec2D+Private.h"
#include <cassert>

namespace djinni_generated {

auto GpsStyleInfo::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::Optional<std::optional, ::djinni_generated::TextureHolderInterface>::toCpp(obj.pointTexture),
            ::djinni_generated::Vec2D::toCpp(obj.pointSizePx),
            ::djinni::Optional<std::optional, ::djinni_generated::TextureHolderInterface>::toCpp(obj.headingTexture),
            ::djinni_generated::Vec2D::toCpp(obj.headingSizePx),
            ::djinni_generated::Color::toCpp(obj.accuracyColor)};
}

auto GpsStyleInfo::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[MCGpsStyleInfo alloc] initWithPointTexture:(::djinni::Optional<std::optional, ::djinni_generated::TextureHolderInterface>::fromCpp(cpp.pointTexture))
                                            pointSizePx:(::djinni_generated::Vec2D::fromCpp(cpp.pointSizePx))
                                         headingTexture:(::djinni::Optional<std::optional, ::djinni_generated::TextureHolderInterface>::fromCpp(cpp.headingTexture))
                                          headingSizePx:(::djinni_generated::Vec2D::fromCpp(cpp.headingSizePx))
                                          accuracyColor:(::djinni_generated::Color::fromCpp(cpp.accuracyColor))];
}

}  // namespace djinni_generated
