// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from layer_gps.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, MCGpsMode)
{
    MCGpsModeDISABLED = 0,
    MCGpsModeSTANDARD = 1,
    MCGpsModeFOLLOW = 2,
    MCGpsModeFOLLOW_AND_TURN = 3,
};
