// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from layer_gps.djinni

#import <Foundation/Foundation.h>

@interface MCGpsCourseInfo : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithAngle:(float)angle
                              scaling:(float)scaling NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)gpsCourseInfoWithAngle:(float)angle
                                       scaling:(float)scaling;

@property (nonatomic, readonly) float angle;

@property (nonatomic, readonly) float scaling;

@end
