// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from layer_gps.djinni
#ifdef __cplusplus

#import "MCGpsCourseInfo.h"
#include "GpsCourseInfo.h"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class MCGpsCourseInfo;

namespace djinni_generated {

struct GpsCourseInfo
{
    using CppType = ::GpsCourseInfo;
    using ObjcType = MCGpsCourseInfo*;

    using Boxed = GpsCourseInfo;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

} // namespace djinni_generated
#endif
