// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from layer_gps.djinni

#import "MCGpsCourseInfo+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto GpsCourseInfo::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::F32::toCpp(obj.angle),
            ::djinni::F32::toCpp(obj.scaling)};
}

auto GpsCourseInfo::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[MCGpsCourseInfo alloc] initWithAngle:(::djinni::F32::fromCpp(cpp.angle))
                                          scaling:(::djinni::F32::fromCpp(cpp.scaling))];
}

} // namespace djinni_generated
