// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from layer_gps.djinni

package io.openmobilemaps.mapscore.shared.gps

enum class GpsMode {
    DISABLED,
    STANDARD,
    FOLLOW,
    FOLLOW_AND_TURN,
}
