// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from layer_gps.djinni

#pragma once

enum class GpsMode;

class GpsLayerCallbackInterface {
public:
    virtual ~GpsLayerCallbackInterface() {}

    virtual void modeDidChange(GpsMode mode) = 0;
};
