// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from layer_gps.djinni

#pragma once

#include "Color.h"
#include "TextureHolderInterface.h"
#include "Vec2D.h"
#include <memory>
#include <optional>
#include <utility>

struct GpsStyleInfo final {
    std::shared_ptr<::TextureHolderInterface> pointTexture;
    ::Vec2D pointSizePx;
    std::shared_ptr<::TextureHolderInterface> headingTexture;
    ::Vec2D headingSizePx;
    ::Color accuracyColor;

    GpsStyleInfo(std::shared_ptr<::TextureHolderInterface> pointTexture_,
                 ::Vec2D pointSizePx_,
                 std::shared_ptr<::TextureHolderInterface> headingTexture_,
                 ::Vec2D headingSizePx_,
                 ::Color accuracyColor_)
    : pointTexture(std::move(pointTexture_))
    , pointSizePx(std::move(pointSizePx_))
    , headingTexture(std::move(headingTexture_))
    , headingSizePx(std::move(headingSizePx_))
    , accuracyColor(std::move(accuracyColor_))
    {}
};
