// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from layer_gps.djinni

#pragma once

#include "GpsCourseInfo.h"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeGpsCourseInfo final {
public:
    using CppType = ::GpsCourseInfo;
    using JniType = jobject;

    using Boxed = NativeGpsCourseInfo;

    ~NativeGpsCourseInfo();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeGpsCourseInfo();
    friend ::djinni::JniClass<NativeGpsCourseInfo>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("io/openmobilemaps/gps/shared/gps/GpsCourseInfo") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(FF)V") };
    const jfieldID field_angle { ::djinni::jniGetFieldID(clazz.get(), "angle", "F") };
    const jfieldID field_scaling { ::djinni::jniGetFieldID(clazz.get(), "scaling", "F") };
};

} // namespace djinni_generated
