name: Dependencies PR

on:
  workflow_dispatch:
    inputs:
      mapsCoreBranch:
        description: The branch of the maps-core build
        required: true
        type: string
      mapsCoreCommitHash:
        description: The commit hash of the maps-core build
        required: true
        type: string
      mapsCoreArtifactId:
        description: The Android artifact ID for maps-core
        required: true
        type: string
      mapsCoreArtifactVersion:
        description: The Android artifact version for maps-core
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Create dependencies update PR
        run: |
          # Replace Android dependency
          sed -i -E 's|(openmobilemaps:)(mapscore.*)|\1${{ inputs.mapsCoreArtifactId }}:${{ inputs.mapsCoreArtifactVersion }}"|g' android/build.gradle
          
          # Replace iOS dependency
          sed -i -E 's|(openmobilemaps\/maps-core".*)"(..*)"|\1"${{ inputs.mapsCoreBranch }}"|g' Package.swift
          json=$(cat Package.resolved | jq '.object.pins |= map(if .package == "MapCore" then .state.branch = "${{ inputs.mapsCoreBranch }}" | .state.revision = "${{ inputs.mapsCoreCommitHash }}" else . end)');
          echo "$json" > Package.resolved;
      - name: Create commit
        uses: EndBug/add-and-commit@v9.1.3
        with:
          message: "Update maps-core dependency"
          new_branch: "feature/update-mapscore"
      - name: Create pull request
        run: |
          gh pr create --base develop --head feature/update-mapscore --title 'Update maps-core dependency' --body 'Update maps-core to ${{ inputs.mapsCoreBranch }} (${{ inputs.mapsCoreCommitHash }})'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}