name: android

on:
  workflow_dispatch:
    inputs:
      mapsCoreCommitHash:
        description: The commit hash of the maps-core build
        required: true
        type: string
      mapsCoreArtifactId:
        description: The Android artifact ID for maps-core
        required: true
        type: string
      mapsCoreArtifactVersion:
        description: The Android artifact version for maps-coe
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
      - name: Create dependencies update PR
        run: |
          echo "Updating ${{ inputs.mapsCoreArtifactId }} to ${{ inputs.mapsCoreArtifactVersion }} (${{ inputs.mapsCoreCommitHash }})"
