name: ios

env:
  XCODE_VERSION: 'Xcode_16.0'

on:
  pull_request:
    branches: [ main, develop, release/** ]

jobs:
  build:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Switch to Xcode ${{ env.XCODE_VERSION }}
      run: sudo xcode-select --switch /Applications/${{ env.XCODE_VERSION }}.app
    - name: Build
      run: xcodebuild -scheme LayerGps -destination 'platform=iOS Simulator,OS=18.0,name=iPhone 16 Pro'
